### ISSUE TITLE
need styling of a hover or something on the nutrients. Helps to realize these are clickable

### ISSUE THREAD

**Issue by emtrimble** [llancon/Healthy-Start#103]

**Comment by dummied** [comment]
Also: Remove the `_` from the nutrient names.

https://www.dropbox.com/s/pofhyuibkdxnusd/Screenshot%202016-12-14%2013.06.59.png?dl=0

**Comment by kbrook10** [comment]
commit 76b51ed2616dd5925294ee44f9d25b9acd5ba58f

`+.ns--nutritionlist li.ns-listItem:hover {
 +  background-color: #66ccff;
 +  color: #fff;
 +}
 +`
