### ISSUE TITLE
It's an API. You likely don't want to render a form

### ISSUE THREAD

**Issue by dummied** [llancon/Healthy-Start#84]
https://github.com/llancon/Healthy-Start/blob/master/app/controllers/users_controller.rb#L20

Also, edit itself doesn't make a lot of sense:

https://github.com/llancon/Healthy-Start/blob/master/app/controllers/users_controller.rb#L9-L12

**Comment by luis-iron-yard** [comment]
deleted edit and now instead of rendering a form it will render a json error message
