### ISSUE TITLE
Remove debugging code

### ISSUE THREAD

**Issue by dummied** [llancon/Healthy-Start#89]
Some examples:

- https://github.com/llancon/Healthy-Start/blob/master/app/controllers/favorites_controller.rb#L5
- https://github.com/llancon/Healthy-Start/blob/master/app/controllers/quotes_controller.rb#L5
- https://github.com/llancon/Healthy-Start/blob/master/app/controllers/recipes_controller.rb#L18
- https://github.com/llancon/Healthy-Start/blob/master/app/controllers/recipes_controller.rb#L27

**Comment by luis-iron-yard** [comment]
Took all extra debugging code.
